name: test_xmake_shared_link_chain_with_add_package

on:
  - push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Format by stylua
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.20.0 # NOTE: we recommend pinning to a specific version in case of formatting changes
          # CLI arguments
          args: ${{ github.workspace }}/ xmake.lua

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: lua-format-bot
          commit_message: "Automated commit of stylua-action changes."
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        version: [latest, branch@master, branch@dev]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: xmake-io/github-action-setup-xmake@master
        with:
          xmake-version: ${{ matrix.version }}
      - name: Run setup xmake and test
        run: |
          xmake --version

      - name: Test build
        working-directory: ${{ github.workspace }}
        # continue-on-error: true
        run: |
          xmake q -y
          xmake -vD
          xmake install -o ${{ github.workspace }}/.install
          xmake run main
          ./${{ github.workspace }}/.install/main

      - name: Check rpath when with ubuntu
        working-directory: ${{ github.workspace }}
        if: (success() || failure()) && (matrix.os == 'ubuntu-latest')
        run: |
          ldd ./build/linux/x86_64/release/libmydylib.so

      - name: Check rpath when with macOS
        working-directory: ${{ github.workspace }}
        if: (success() || failure()) && (matrix.os == 'macOS-latest')
        run: |
          otool -L ./build/macosx/x86_64/release/main
          otool -L ./build/macosx/x86_64/release/libmydylib.dylib
